[global]
developmentMode = false

[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[client]
caching = true
displayEnabled = true

[theme]
primaryColor = "#00d4ff"
backgroundColor = "#080c16"
secondaryBackgroundColor = "#0f1422"
textColor = "#e2e8f0"
font = "monospace"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[mapbox]
token = ""

